#!/bin/bash -e
    
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
pip install --upgrade "virtualenv" "GitPython>=0.3.6" "jsonschema" "argcomplete"

activate-global-python-argcomplete

chmod a+rwx /var/oebuild

#DEBHELPER#
